# Generated by Django 3.1.2 on 2020-11-04 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=250)),
                ('photo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=250)),
                ('photo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_title', models.CharField(max_length=250)),
                ('photo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=200)),
                ('occassion', models.CharField(blank=True, max_length=200)),
                ('mood', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('file_type', models.CharField(max_length=10)),
                ('yr_of_rel', models.IntegerField()),
                ('lyrics', models.TextField(blank=True)),
                ('popularity', models.IntegerField()),
                ('album', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='music_app.album')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.movie')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.singer')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_title', models.CharField(max_length=200)),
                ('add_to_playlist', models.ManyToManyField(blank=True, to='music_app.Songs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
